/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AppRouteImport } from './routes/_app'
import { Route as AppIndexRouteImport } from './routes/_app.index'
import { Route as AppSentencesRouteImport } from './routes/_app.sentences'
import { Route as AppReviewRouteImport } from './routes/_app.review'
import { Route as AppQuizRouteImport } from './routes/_app.quiz'
import { Route as AppProfileRouteImport } from './routes/_app.profile'
import { Route as AppImportRouteImport } from './routes/_app.import'
import { Route as AppWordsIndexRouteImport } from './routes/_app.words.index'
import { Route as AppWordsAddRouteImport } from './routes/_app.words.add'
import { Route as AppWordsIdRouteImport } from './routes/_app.words.$id'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppSentencesRoute = AppSentencesRouteImport.update({
  id: '/sentences',
  path: '/sentences',
  getParentRoute: () => AppRoute,
} as any)
const AppReviewRoute = AppReviewRouteImport.update({
  id: '/review',
  path: '/review',
  getParentRoute: () => AppRoute,
} as any)
const AppQuizRoute = AppQuizRouteImport.update({
  id: '/quiz',
  path: '/quiz',
  getParentRoute: () => AppRoute,
} as any)
const AppProfileRoute = AppProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AppRoute,
} as any)
const AppImportRoute = AppImportRouteImport.update({
  id: '/import',
  path: '/import',
  getParentRoute: () => AppRoute,
} as any)
const AppWordsIndexRoute = AppWordsIndexRouteImport.update({
  id: '/words/',
  path: '/words/',
  getParentRoute: () => AppRoute,
} as any)
const AppWordsAddRoute = AppWordsAddRouteImport.update({
  id: '/words/add',
  path: '/words/add',
  getParentRoute: () => AppRoute,
} as any)
const AppWordsIdRoute = AppWordsIdRouteImport.update({
  id: '/words/$id',
  path: '/words/$id',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AppIndexRoute
  '/login': typeof LoginRoute
  '/import': typeof AppImportRoute
  '/profile': typeof AppProfileRoute
  '/quiz': typeof AppQuizRoute
  '/review': typeof AppReviewRoute
  '/sentences': typeof AppSentencesRoute
  '/words/$id': typeof AppWordsIdRoute
  '/words/add': typeof AppWordsAddRoute
  '/words/': typeof AppWordsIndexRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/import': typeof AppImportRoute
  '/profile': typeof AppProfileRoute
  '/quiz': typeof AppQuizRoute
  '/review': typeof AppReviewRoute
  '/sentences': typeof AppSentencesRoute
  '/': typeof AppIndexRoute
  '/words/$id': typeof AppWordsIdRoute
  '/words/add': typeof AppWordsAddRoute
  '/words': typeof AppWordsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/_app/import': typeof AppImportRoute
  '/_app/profile': typeof AppProfileRoute
  '/_app/quiz': typeof AppQuizRoute
  '/_app/review': typeof AppReviewRoute
  '/_app/sentences': typeof AppSentencesRoute
  '/_app/': typeof AppIndexRoute
  '/_app/words/$id': typeof AppWordsIdRoute
  '/_app/words/add': typeof AppWordsAddRoute
  '/_app/words/': typeof AppWordsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/import'
    | '/profile'
    | '/quiz'
    | '/review'
    | '/sentences'
    | '/words/$id'
    | '/words/add'
    | '/words/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/import'
    | '/profile'
    | '/quiz'
    | '/review'
    | '/sentences'
    | '/'
    | '/words/$id'
    | '/words/add'
    | '/words'
  id:
    | '__root__'
    | '/_app'
    | '/login'
    | '/_app/import'
    | '/_app/profile'
    | '/_app/quiz'
    | '/_app/review'
    | '/_app/sentences'
    | '/_app/'
    | '/_app/words/$id'
    | '/_app/words/add'
    | '/_app/words/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRoute: typeof AppRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/sentences': {
      id: '/_app/sentences'
      path: '/sentences'
      fullPath: '/sentences'
      preLoaderRoute: typeof AppSentencesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/review': {
      id: '/_app/review'
      path: '/review'
      fullPath: '/review'
      preLoaderRoute: typeof AppReviewRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/quiz': {
      id: '/_app/quiz'
      path: '/quiz'
      fullPath: '/quiz'
      preLoaderRoute: typeof AppQuizRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/profile': {
      id: '/_app/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AppProfileRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/import': {
      id: '/_app/import'
      path: '/import'
      fullPath: '/import'
      preLoaderRoute: typeof AppImportRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/words/': {
      id: '/_app/words/'
      path: '/words'
      fullPath: '/words/'
      preLoaderRoute: typeof AppWordsIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/words/add': {
      id: '/_app/words/add'
      path: '/words/add'
      fullPath: '/words/add'
      preLoaderRoute: typeof AppWordsAddRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/words/$id': {
      id: '/_app/words/$id'
      path: '/words/$id'
      fullPath: '/words/$id'
      preLoaderRoute: typeof AppWordsIdRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppImportRoute: typeof AppImportRoute
  AppProfileRoute: typeof AppProfileRoute
  AppQuizRoute: typeof AppQuizRoute
  AppReviewRoute: typeof AppReviewRoute
  AppSentencesRoute: typeof AppSentencesRoute
  AppIndexRoute: typeof AppIndexRoute
  AppWordsIdRoute: typeof AppWordsIdRoute
  AppWordsAddRoute: typeof AppWordsAddRoute
  AppWordsIndexRoute: typeof AppWordsIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppImportRoute: AppImportRoute,
  AppProfileRoute: AppProfileRoute,
  AppQuizRoute: AppQuizRoute,
  AppReviewRoute: AppReviewRoute,
  AppSentencesRoute: AppSentencesRoute,
  AppIndexRoute: AppIndexRoute,
  AppWordsIdRoute: AppWordsIdRoute,
  AppWordsAddRoute: AppWordsAddRoute,
  AppWordsIndexRoute: AppWordsIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AppRoute: AppRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
