// This file is automatically generated. Do not edit it directly.
import { createMiddleware } from '@tanstack/react-start'
import { getRequest } from '@tanstack/react-start/server'
import { createClient } from '@supabase/supabase-js'
import type { Database } from './types'



export const requireSupabaseAuth = createMiddleware({ type: 'function' }).server(
  async ({ next }) => {
    const SUPABASE_URL = process.env.SUPABASE_URL;
    const SUPABASE_PUBLISHABLE_KEY = process.env.SUPABASE_PUBLISHABLE_KEY;

    if (!SUPABASE_URL || !SUPABASE_PUBLISHABLE_KEY) {
      console.error('[Supabase] Missing env variables');
      return next({ context: {} as any });
    }

    const request = getRequest();
    const authHeader = request?.headers?.get('authorization');

    if (!authHeader?.startsWith('Bearer ')) {
      return next({ context: {} as any });
    }

    const token = authHeader.replace('Bearer ', '');
    if (!token) {
      return next({ context: {} as any });
    }

    const supabase = createClient<Database>(
      SUPABASE_URL,
      SUPABASE_PUBLISHABLE_KEY,
      {
        global: { headers: { Authorization: `Bearer ${token}` } },
        auth: { storage: undefined, persistSession: false, autoRefreshToken: false },
      }
    );

    const { data, error } = await supabase.auth.getUser(token);
    if (error || !data?.user) {
      return next({ context: {} as any });
    }

    return next({ context: { supabase, userId: data.user.id } });
  },
);
